### ISSUE TITLE
Trouble communicating between the client and server 

### ISSUE THREAD

**Issue by mackenziewillborn** [mackenziewillborn/bme547final#12]
We are having some difficulty communicating between the client and the server with mongoDB. I am able to save new users to the database just using the server alone, so the database is set up correctly, however when the client is involved we can't upload to the database! All of the code is in the mlw60/user_name_transfer branch for the server, client, and class that I am using.

Can you see anything we need to change?

**Comment by dward2** [comment]
This is the kind of thing that is so hard to capture, because we make assumptions about what is written in the code versus what is actually there.  I do this all the time.

Your client is making the following POST request:
https://github.com/mackenziewillborn/bme547final/blob/447cf9e1889becbe66416ac7fbff8d69f9a8b2e6/mongo_client.py#L6

The server is set up to listen for this route:
https://github.com/mackenziewillborn/bme547final/blob/447cf9e1889becbe66416ac7fbff8d69f9a8b2e6/mongo_server.py#L20

You are making a post request to `/new_user`, but the server is listening for `/user_name`.  
Hence, nothing is happening.

**Comment by dward2** [comment]
How did I figure this out.  I debugged the code line by line.  I set up a breakpoint in the server code in the first line of the function after the `@app.route` decorator.  Then, I started the server in debug mode.  

Next, I went to the client code, set a breakpoint on the first line, and then started it in debug mode.  I stepped through the client code line by line, and when it reached the POST command, the server was never activated.  That told me that there was no communication to the server.  I then looked to see why, and saw the different in routes.  

So, consider adding to your approach when debugging to step through your code line by line when it isn't doing what you think it should be doing.
