### ISSUE TITLE
Problem with u.save() over riding previously saved user info

### ISSUE THREAD

**Issue by mackenziewillborn** [mackenziewillborn/bme547final#17]
We are having issues updating each user with more information as we enter new info using the client. It seems that each time we use u.save in a function, it overrides what we saved in the last function. Are there any other ways to update the class information without over riding it? 

Below is a simple example of our problem. If we run this server without trying to save a process type, we can see the time stamp. Once we send a processing type, you can no longer see the time stamp associate with that user in MongoDB. 

from flask_pymongo import PyMongo
from flask import Flask, request
from my_class import User
from pymodm import connect
import datetime

app = Flask(__name__)

connect("mongodb+srv://mlw60:Wm347609@bme547-r5nv9."
        "mongodb.net/test?retryWrites=true")

app.config['MONGO_DBNAME'] = "bme547"
app.config['MONGO_URI'] = "mongodb+srv://mlw60:Wm347609@bme547-r5nv9." \
                          "mongodb.net/test?retryWrites=true"

mongo = PyMongo(app)

def add_user_name(user_name_arg, time):
    u = User(user_name=user_name_arg,
             time_uploaded=time)
    u.save()

def add_processing_type(user_name_arg, processing_type_arg):
    u = User(user_name=user_name_arg,
             processing_type=processing_type_arg)
    u.save()

def upload_time():
    time_stamp = datetime.datetime.now()
    return time_stamp

@app.route("/user_name", methods=["POST"])
def user_name():
    r = request.get_json()
    user_name = r["user_name"]
    time = upload_time()
    add_user_name(user_name, time)
    return "Added user name!"

@app.route("/processing_type", methods=["POST"])
def processing_type():
    r = request.get_json()
    user_name = r["user_name"]
    processing_type = r["processing_type"]
    add_processing_type(user_name, processing_type)
    return "Added user's image processing type preference!"

if __name__ == '__main__':
    app.run()

**Comment by dward2** [comment]
In your `add_processing_type()` function, you are defining a whole new instance of the `User` class, giving it values for user_name and processing_type.  But, it doesn't have a value for the time_uploaded because it is a brand new instance and you haven't assigned it a value.  So, when you go to save this new instance to the database, it overwrites the existing entry with this new entry that doesn't have a time_uploaded.

Instead, what you need to do is this:
```
def add_processing_type(user_name_arg, processing_type_arg):
    u = JLWUser.objects.raw({"_id": user_name_arg}).first()
    u.processing_type = processing_type_arg
    u.save()
```
Instead of defining a new instance of the class, you retrieve the existing entry from the database using the first line above and store it in a variable, in this case `u`.  Then, you can add to this variable the new field you want to add as is done in the second line.  Then, you resave this to the database.

This change worked for me.  Give it a try and see if it works for you.

Just as a reminder, since I was retrieving an item from the database using the primary key, I needed to look for the `_id` field instead of the `user_name` field.

**Comment by dward2** [comment]
A note about your original post.  Cutting and pasting code such as you did loses the formatting, so I had to spend some time reformatting it.  There are two better approaches.

The first would be to put the code you want me to run/test in a file and push it to your repository.  Then, you can link to that code in your issue.

Second, if you need to put code into an issue, use "```" at the start and end of the code block to make it look like code.  For example:

```
def test_code(parameter):
    print(x)
    return
```
Click on the "..." in the upper right of this post and choose edit to see what it looks like raw.

**Comment by dward2** [comment]
One more thing.  If you want more info on this issue, visit <https://pymodm.readthedocs.io/en/latest/getting-started.html#updating-documents>
