### ISSUE TITLE
pep8 error with matplotlib import

### ISSUE THREAD

**Issue by kelseyli143** [mackenziewillborn/bme547final#37]
I was having a lot of trouble running matplotlib on my computer, but was able to get it to work by using the "matplotlib.use('TkAgg')" command. In my imports, I need all of these statements:
```
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

```
but it only runs successfully if the "matplotlib.use('TkAgg')" command is placed immediately after the "import matplotlib" statement. 

However, when I put the code in this order, I get a pep8 error because I have an import statement after a regular line of code. If I try to put the "import matplotlib.pyplot as plt"
line first, the code breaks as well.  How do I fix this issue?

**Comment by dward2** [comment]
Try this:  Rather than having the `import matplotlib.pyplot as plt` in the first section of code, include it inside of each function that needs to access `matplotlib.pyplot`.  That should eliminate the PEP8 error becuase this import inside the function will be before any code in the function.

But, if that doesn't work or if it seems to need to be in the global part of the code, keep it after the `matplotlib.use('TkAgg')` line.  It is well documented that this statement needs to be before any further imports.  And, just add something to your readme file about this and we'll ignore that particular PEP8 issue.
